name: Test on PR
on:
  pull_request

jobs:
  test:
    name: Test Pinelab-storefront x Vendure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: packages/e2e
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build Vendure
        run: cd ../../vendure/ && npm install
      - name: Build Pinelab-storefront
        run: cd ../pinelab-storefront && yarn
      - name: Build e2e
        run: yarn
      - name: Test
        run: yarn vitest:e2e
